name: test lerna repo CI

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Please enter your github name'
        required: true
      email:
        description: 'Please enter your github email'
        required: true
      version:
        description: 'Please enter your release version'
        required: true
        
jobs:

  readyGo:

    runs-on: ubuntu-latest

    env: 
      PUBLISH_OPTS: ${{ github.ref_name == 'master' && '--verbose' || '--verbose --tag=alpha' }}
    
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.14.0
          registry-url: https://registry.npmjs.org/
      
      - name: set git config
        run: |
          git config --global user.email ${{ github.event.inputs.email }}
          git config --global user.name ${{ github.event.inputs.name }}
          
      - name: install package
        run: |
          npm ci
          
      - name: lerna version
        run: |
          lerna version $VERSION --yes
        env:
          VERSION: ${{ github.event.inputs.version }}
          
      - name: publish lib
        if: ${{ github.ref_name == 'master' }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          lerna publish from-package --yes
          echo "publish:lib successfully 🚀"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          
      - name: publish rc
        if: ${{ github.ref_name != 'master' }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          lerna publish from-package --yes --canary --pre-dist-tag=rc --preid=rc
          echo "publish:rc successfully 🚀"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
